version: "3"
services:
  mysql:
    build: .
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: work
      TZ: "Asia/Tokyo"
    working_dir: /var/lib/mysql
    command: mysqld --sql_mode="" --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    #volumes:
    #  - ./db:/var/lib/mysql
